version: '3.9'

services:
  postgres:
    container_name: db-postgres
    image: postgres:14-alpine
    ports:
      - 5400:5432
    volumes:
      - ./.postgres:/var/lib/postgresql/data
    env_file:
      - .env
